apiVersion: apps/v1
kind: Deployment
metadata:
  name: scriptservice
  labels:
    app: scriptservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scriptservice
  template:
    metadata:
      labels:
        app: scriptservice
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: scriptservice
          image: user0514acr.azurecr.io/scriptservice:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
