apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiservice
  labels:
    app: aiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiservice
  template:
    metadata:
      labels:
        app: aiservice
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: aiservice
          image: "jaekyung959/aiservice:v1"
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              value: 감자튀김
            - name: TZ
              value: Asia/Seoul            
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
